### ISSUE TITLE
(Back) Sync Api

### ISSUE THREAD

**Issue by ErikSin** [digidem/mapeo-core-docs#3]
Using the methodology of Document Driven Development, document the new sync API.

Refer to this notion document for an overview of the current sync: https://www.notion.so/digidem/Sync-Api-79d1a6f64f8f401cbeb897f8f1c9ee89 

To Do
- [ ] Review Notion document, and based of the proposed new sync, document functions needed for the sync API. Inculde parameter types, and return types.
- [ ] Review hypercore state discussion (found at the bottom of the notion doc)
- [ ] If needed, schedule another discussion to talk about hypercore state api
- [ ] Document hypercore state functions

**Comment by achou11** [comment]
Closing since no longer relevant
